line-length = 120
target-version = "py312"

[lint]
# 严格模式：启用 Ruff 全规则。
select = ["ALL"]
ignore = ["D203", "D213", "D400", "D415", "RUF001", "RUF002", "RUF003", "COM812"]

[lint.per-file-ignores]
"tests/**/*.py" = ["S101"]
"GuiCore/**/__init__.py" = ["N999"]
"GuiCore/**/*.py" = [
]
"GUI/**/__init__.py" = ["N999"]
"GUI/**/*.py" = [
	"PLR0915",
]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
