from __future__ import annotations

import ast
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = ROOT / "docs"
PACKAGES = ("AppCore", "GUI", "GuiCore")


@dataclass(frozen=True)
class ApiItem:
    kind: str
    name: str
    lineno: int


def _iter_python_files() -> Iterable[Path]:
    for package in PACKAGES:
        base = ROOT / package
        if not base.exists():
            continue
        for path in sorted(base.rglob("*.py")):
            if "__pycache__" in path.parts:
                continue
            yield path


def _module_name(path: Path) -> str:
    rel = path.relative_to(ROOT).with_suffix("")
    return ".".join(rel.parts)


def _collect_api(path: Path) -> list[ApiItem]:
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source)
    items: list[ApiItem] = []
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            items.append(ApiItem(kind="class", name=node.name, lineno=node.lineno))
        if isinstance(node, ast.FunctionDef) and not node.name.startswith("_"):
            items.append(ApiItem(kind="function", name=node.name, lineno=node.lineno))
    return items


def _top_package(module: str | None) -> str | None:
    if not module:
        return None
    head = module.split(".", 1)[0]
    if head in PACKAGES:
        return head
    return None


def _collect_edges(path: Path) -> set[tuple[str, str]]:
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source)
    current = path.relative_to(ROOT).parts[0]
    edges: set[tuple[str, str]] = set()

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                target = _top_package(alias.name)
                if target and target != current:
                    edges.add((current, target))
        elif isinstance(node, ast.ImportFrom):
            target = _top_package(node.module)
            if target and target != current:
                edges.add((current, target))
    return edges


def generate_architecture_md(edges: set[tuple[str, str]]) -> str:
    edge_lines = []
    for source, target in sorted(edges):
        edge_lines.append(f"    {source} --> {target}")

    edge_block = "\n".join(edge_lines) if edge_lines else "    AppCore --> GUI"

    return f"""# Architecture

This file is auto-generated by scripts/generate_docs.py.

## High-Level Layers

- AppCore: app context, config loading, modules, logging, tool adapters
- GUI: windows and page assembly
- GuiCore: reusable UI components and style system

## Dependency Graph

```mermaid
flowchart LR
    AppCore[AppCore]
    GUI[GUI]
    GuiCore[GuiCore]

{edge_block}
```
"""


def generate_api_md(api_map: dict[str, list[ApiItem]]) -> str:
    lines = [
        "# API Reference",
        "",
        "This file is auto-generated by scripts/generate_docs.py.",
        "",
    ]

    for module in sorted(api_map):
        lines.append(f"## {module}")
        items = api_map[module]
        if not items:
            lines.append("")
            lines.append("- No public top-level classes or functions")
            lines.append("")
            continue

        lines.append("")
        for item in sorted(items, key=lambda x: (x.kind, x.name)):
            lines.append(f"- {item.kind}: `{item.name}` (line {item.lineno})")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def generate_index_md() -> str:
    return """# Documentation

This folder is generated by scripts/generate_docs.py.

- [Architecture](ARCHITECTURE.md)
- [API Reference](API.md)
- [Legacy Compatibility](LEGACY_COMPATIBILITY.md)
"""


def main() -> None:
    DOCS_DIR.mkdir(parents=True, exist_ok=True)

    api_map: dict[str, list[ApiItem]] = {}
    edges: set[tuple[str, str]] = set()
    for path in _iter_python_files():
        module = _module_name(path)
        api_map[module] = _collect_api(path)
        edges.update(_collect_edges(path))

    (DOCS_DIR / "ARCHITECTURE.md").write_text(
        generate_architecture_md(edges), encoding="utf-8"
    )
    (DOCS_DIR / "API.md").write_text(generate_api_md(api_map), encoding="utf-8")
    (DOCS_DIR / "README.md").write_text(generate_index_md(), encoding="utf-8")


if __name__ == "__main__":
    main()